version: '3.7'

services:
  db:
    image: mysql
    container_name: company-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./db/.env
    build: ./db
    ports:
      - '3307:3306' # The port number 3306 is normally set as default and occupied by the local mysql database
    expose:
      - '3307'
  server:
    container_name: company-server
    restart: on-failure
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
    build: ./server
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - db
    volumes:
      - ./server:/home/node/app
      - ./server/node_modules:/home/node/app/node_modules
volumes:
  node_modules:
